export const DISTRICTS_BY_ISLAND: Record<'mahe' | 'praslin', string[]> = {
  mahe: [
    "Anse aux Pins",
    "Anse Boileau",
    "Anse Etoile",
    "Anse Royale",
    "Au Cap",
    "Baie Lazare",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Cascade",
    "English River",
    "Glacis",
    "Grand'Anse Mahé",
    "Les Mamelles",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Pointe La Rue",
    "Port Glaud",
    "Roche Caïman",
    "Saint Louis",
    "Takamaka",
  ],
  praslin: ["Baie Sainte Anne", "Grand'Anse Praslin"],
}
